name: Swift (Xcode)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode 16
      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
  
    - name: Resolve SwiftPM dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Build for macOS
      run: xcodebuild -scheme "HexSecApp" -destination 'platform=macOS' build

    - name: Test for macOS
      run: xcodebuild -scheme "HexSecApp" -destination 'platform=macOS' test

    - name: Test for iPhone
      run: xcodebuild -scheme "HexSecApp" -destination 'platform=iOS Simulator,name=iPhone 16' test

    - name: Test for iPad
      run: xcodebuild -scheme "HexSecApp" -destination 'platform=iOS Simulator,name=iPad (10th generation)' test
